// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: hmi screen 3 manual

#ifndef _HMI_SCREEN_3_MANUAL_UI_H
#define _HMI_SCREEN_3_MANUAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image4;
void ui_event_pump(lv_event_t * e);
extern lv_obj_t * ui_pump;
void ui_event_vacum(lv_event_t * e);
extern lv_obj_t * ui_vacum;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Switch1;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_pojok_kiri_atas_screen_1_png);    // assets/pojok kiri atas screen 1.png
LV_IMG_DECLARE(ui_img_pojok_kiri_bawah_png);    // assets/pojok kiri bawah.png
LV_IMG_DECLARE(ui_img_pojok_kanan_bawah_screen_1_png);    // assets/pojok kanan bawah screen 1.png
LV_IMG_DECLARE(ui_img_pojok_kanan_atas_png);    // assets/pojok kanan atas.png
LV_IMG_DECLARE(ui_img_gambar_orang_new_screen1_png);    // assets/gambar orang new screen1.png
LV_IMG_DECLARE(ui_img_font_smart_handglove_png);    // assets/font smart handglove.png
LV_IMG_DECLARE(ui_img_screen_2_new_julyyy_png);    // assets/screen 2 new julyyy.png
LV_IMG_DECLARE(ui_img_up_green_png);    // assets/up green.png
LV_IMG_DECLARE(ui_img_down_red_png);    // assets/down red.png
LV_IMG_DECLARE(ui_img_patient_health_tracker_font_png);    // assets/patient health tracker font.png
LV_IMG_DECLARE(ui_img_smarthandglove_logonew_png);    // assets/smarthandglove logonew.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
