// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: hmi screen 3 manual

#include "ui.h"


void ui_event_comp_Switch1_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_Switch1 = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(comp_Switch1[UI_COMP_SWITCH1_SWITCH1], LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

// COMPONENT Switch1

lv_obj_t * ui_Switch1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Switch1;
    cui_Switch1 = lv_switch_create(comp_parent);
    lv_obj_set_width(cui_Switch1, 61);
    lv_obj_set_height(cui_Switch1, 32);
    lv_obj_set_x(cui_Switch1, 264);
    lv_obj_set_y(cui_Switch1, 157);
    lv_obj_set_align(cui_Switch1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Switch1, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags

    lv_obj_set_style_bg_color(cui_Switch1, lv_color_hex(0xE91919), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCH1_NUM);
    children[UI_COMP_SWITCH1_SWITCH1] = cui_Switch1;
    lv_obj_add_event_cb(cui_Switch1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Switch1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Switch1, ui_event_comp_Switch1_Switch1, LV_EVENT_ALL, children);
    ui_comp_Switch1_create_hook(cui_Switch1);
    return cui_Switch1;
}
