// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: hmi screen 3 manual

#ifndef _HMI_SCREEN_3_MANUAL_UI_COMP_HOOK_H
#define _HMI_SCREEN_3_MANUAL_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Switch1_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
