// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: hmi screen 3 manual

#ifndef _UI_COMP_SWITCH1_H
#define _UI_COMP_SWITCH1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Switch1
#define UI_COMP_SWITCH1_SWITCH1 0
#define _UI_COMP_SWITCH1_NUM 1
lv_obj_t * ui_Switch1_create(lv_obj_t * comp_parent);
void ui_event_comp_Switch1_Switch1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
